const SYNC_DIRNAME = '.config';
const SYNC_CONFIG_FILENAME = 'sync-config.json';
const TTS_CONFIG_FILENAME = 'tts-config.json';
const SYNC_STATE_FILENAME = 'sync-state.json';
const SYNC_LOCK_FILENAME = 'sync.lock';

export { SYNC_DIRNAME, SYNC_CONFIG_FILENAME, TTS_CONFIG_FILENAME, SYNC_STATE_FILENAME, SYNC_LOCK_FILENAME };
export default {
  SYNC_DIRNAME,
  SYNC_CONFIG_FILENAME,
  TTS_CONFIG_FILENAME,
  SYNC_STATE_FILENAME,
  SYNC_LOCK_FILENAME
};
